### ISSUE TITLE
multivariate_timeseriesweka

### ISSUE THREAD

**Issue by TonyBagnall** [TonyBagnall/uea-tsc#11]
I propose we keep this off the repo for now, until it is better documented and structured. Thoughts?

**Comment by goastler** [comment]
Perhaps you could make a branch for the multivariate stuff? Would allow it to be as messy as required for now but still be on the repo so you can use other code alongside

**Comment by TonyBagnall** [comment]
yes that seems a good idea. However,
1. I'm not sure how to technically do it without cloning to my local. Also, others branches seems to by in origin/dev or somesuch. 
2. I'm not sure how it works. If a branch contains a super set of code from the master, and then the master changes, can you update the branch whilst leaving the code in the branch all unchanged?  Or does only code different to master go into branch (i.e. a reference to code rather than a clone of code)?
