### ISSUE TITLE
timeseriesweka.classifiers

### ISSUE THREAD

**Issue by TonyBagnall** [TonyBagnall/uea-tsc#12]
1. FastWWS: This is for Petijean DTW. It should be refactored to somewhere more sensible
2. boss: these are variants for the IDA paper. I think they can go
3. cote: Do we use these? 
4. ensembles. This seems a bit ad hoc
5. randomboss. this should go in Matthews development branch (i.e. local). I think we have maybe two BOSS on the Repo: The original (BOSS) and our best effort so far (RandomBOSS)
 6. Classifiers: I suggest we oganise these in packagages dictionary, shapelet, frequencydomain, interval and timedomain

**Comment by goastler** [comment]
Is FastWWS related to EE? If so I can take a look at it, but could probably do with reading the paper on it also if you've got that to hand / can point me in the right direction

**Comment by TonyBagnall** [comment]
FastWWS is the Fast Window Search, which is a way of speeding up DTW window setting. This is the paper

**Comment by TonyBagnall** [comment]
https://www.francois-petitjean.com/Research/Petitjean2018-SDM-learn-warp-window.pdf

**Comment by TonyBagnall** [comment]
bloody newlines are annoying in this system :) I tested his version vs my fast version and his was 12x faster at a cost of about 50x memory, usually a reasonable trade off. Somewhere I documented the experiments .....
