### ISSUE TITLE
Experiments/ClassifierList

### ISSUE THREAD

**Issue by TonyBagnall** [TonyBagnall/uea-tsc#73]
I need an adaptation to Experiments, ClassifierLists. When contracted, I want the file structure to reflect that. So If I build ShapeletTransformClassifier for 100 hours, results should be in ShapeletTransformClassifier100.

**Comment by James-Large** [comment]
Adaptation finally pushed to dev, forgot about it. 

See [line 91](https://github.com/TonyBagnall/uea-tsc/blob/dev/src/main/java/experiments/ClassifierLists.java) for an example, to be deleted before going to master

setClassifier cases can now safely edit the classifiername in the experimental arguments directly, e.g. to reflect specific parameter setups
