### ISSUE TITLE
Uniform Contracting

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [TonyBagnall/uea-tsc#80]
Of the classifiers that currently have contracting implemented each have done it slightly differently. It would be a good idea to discuss a uniform way to implement contracting into a classifier, or if necessary define different methods of contracting and make it clearer which one each classifier uses (i.e. separate interfaces).

**Comment by MJFlynn** [comment]
To summarise our meeting on 26/06/19: R.e. the contracting interface. Existing methods will suffice. However, the current duration enum should be updated to Java TimeUnit.
