### ISSUE TITLE
Issue in ImpRandomSearch

### ISSUE THREAD

**Issue by dhanhani** [TonyBagnall/uea-tsc#83]
I found what could be a mistake in the code related to the random search for shapelet selection.

In this line in ImpRandomSearch.java:
           Shapelet shape = checkCandidate.process(getTimeSeries(timeSeries,shapelet.var3), shapelet.var1, shapelet.var2, shapelet.var3);
var1 is the length and var2 is the position as stated by a comment preceding it, however the order is actually different in the checkCandidate function which is as follows:
		protected Shapelet checkCandidate(Instance series, int start, int length, int dimension)
This causes some of the selected shapelets to have the length 0 i.e. no content at all.
I found this issue while trying to write the generated shapelets to a file and found some lines to be empty.

**Comment by TonyBagnall** [comment]
cheers for that, we will look at it this week. Tony

**Comment by TonyBagnall** [comment]
should be fixed now witrh PR #86 on dev, thanks for that
